# Generated by Django 4.0 on 2021-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_mean', models.FloatField(default=0)),
                ('area_mean', models.FloatField(default=0)),
                ('smoothness_mean', models.FloatField(default=0)),
                ('compactness_mean', models.FloatField(default=0)),
                ('concavity_mean', models.FloatField(default=0)),
                ('concave_points_mean', models.FloatField(default=0)),
                ('state', models.FloatField(default=0)),
            ],
        ),
    ]
