# Generated by Django 4.0 on 2021-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='area_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='compactness_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='concave_points_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='concavity_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='smoothness_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='state',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='texture_mean',
            field=models.FloatField(default=None, null=True),
        ),
    ]
