# Generated by Django 4.0 on 2021-12-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_alter_cancer_area_mean_alter_cancer_compactness_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='name',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
    ]
