# Generated by Django 4.0 on 2021-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0003_cancer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cancer',
            name='email',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
    ]
