# Generated by Django 4.0 on 2021-12-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hepatitis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hepatitis',
            old_name='steriod',
            new_name='steroid',
        ),
    ]
