# Generated by Django 4.0 on 2021-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hepatitis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hepatitis',
            name='mobile',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
