# Generated by Django 4.0 on 2021-12-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hepatitis', '0002_rename_steriod_hepatitis_steroid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hepatitis',
            old_name='fatique',
            new_name='fatigue',
        ),
        migrations.RenameField(
            model_name='hepatitis',
            old_name='spleen_pallpable',
            new_name='spleen_palpable',
        ),
    ]
